apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: whitelistapikey
spec:
  compiledAdapter: listchecker
  params:
    refreshInterval: 30s
    cachingInterval: 0
    cachingUseCount: 1
    providerUrl: http://listserver.hack.svc.cluster.local:8080/static/keys.txt
    blacklist: false
    entryType: CASE_INSENSITIVE_STRINGS
---
apiVersion: config.istio.io/v1alpha2
kind: instance
metadata:
  name: apikey
spec:
  compiledTemplate: listentry
  params:
    value: request.headers["apikey"] | ""
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: checkkey
spec:
  match: source.labels["istio"] == "ingressgateway"
  actions:
  - handler: whitelistapikey
    instances: [ apikey ]
---