apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.services }}
  labels:
    name: {{ .Values.namespace.services }}
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    istio-injection: enabled