apiVersion: apps/v1
kind: Deployment
metadata:
  name: onetime
  namespace: {{ .Values.namespace.services }}
  labels:
    app: {{ .Chart.Name }}-onetime
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-onetime
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-onetime
    spec:
      containers:
      - name: onetime
        image: bladedancer/onetime:1.0.4
        env:
          - name: PORT
            value: "8080"
        ports:
        - containerPort: {{ .Values.onetime.port }}
        livenessProbe:
          httpGet:
            path: /apibuilderPing.json
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 30