apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: onetime
  namespace: {{ .Values.namespace.services }}
spec:
  gateways:
  - {{ .Values.gateway.name }}.apic-control
  hosts:
  - {{ .Values.gateway.host }}
  http:
  - match:
    - uri:
        prefix: "/onetime/api"
    rewrite:
      authority: onetime.{{ .Values.namespace.services }}.svc.cluster.local:{{ .Values.onetime.port }}
      uri: "/api"
    route:
    - destination:
        host: onetime.{{ .Values.namespace.services }}.svc.cluster.local
        port:
          number: {{ .Values.onetime.port }}
  - match:
    - uri:
        prefix: "/onetime"
    rewrite:
      authority: onetime.{{ .Values.namespace.services }}.svc.cluster.local:{{ .Values.onetime.port }}
      uri: "/"
    route:
    - destination:
        host: onetime.{{ .Values.namespace.services }}.svc.cluster.local
        port:
          number: {{ .Values.onetime.port }}
